version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: kafka-poc-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: kafka-poc-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini


    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181"

    kafka:
      image: wurstmeister/kafka
      ports:
        - "9092"
      environment:
        HOSTNAME_COMMAND: "echo $$(hostname)"
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_PORT: 9092
        BROKER_ID_COMMAND: "docker inspect --format '{{ .Name }}' $$(hostname) | awk -F_ '{ printf $$NF }'"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
